### ISSUE TITLE
Video analysis: not functioning properly with incorrect labels

### ISSUE THREAD

**Issue by zrabbani** [UtkuBulkan/supereye#3]
![image](https://user-images.githubusercontent.com/81477862/116090358-af880200-a69b-11eb-8b38-411a01e806eb.png)

Software Version :
Latest / Production

Module :
A car and biker collide Page - https://supereye.co.uk/watch/?v=2nLOVsesSfU
DRAMATIC ENDING SWAT page - https://supereye.co.uk/watch/?v=quYgG7I0XXH
bear suit prank page- https://supereye.co.uk/watch/?v=ZqGJJeOa0sS
weird sunlight page- https://supereye.co.uk/watch/?v=pCak8M80rEC

Current State :
The create page states that the video has object analysed, but the watch page for them does not have the objects under the context tab. 

Possible Solution :
If possible, have a feature to re-analyse the videos

**Comment by UtkuBulkan** [comment]
A car and biker collide Page - https://supereye.co.uk/watch/?v=2nLOVsesSfU
DRAMATIC ENDING SWAT page - https://supereye.co.uk/watch/?v=quYgG7I0XXH
bear suit prank page- https://supereye.co.uk/watch/?v=ZqGJJeOa0sS
weird sunlight page- https://supereye.co.uk/watch/?v=pCak8M80rEC

All these videos now seem to properly present the objects detected in context tab / watch page.
