### ISSUE TITLE
Uploaded videos should be resized automatically 

### ISSUE THREAD

**Issue by zrabbani** [UtkuBulkan/supereye#6]
Software Version :
Latest / Production

Module :
Create page/watch page

Current State :
Currently, uploaded videos are posted in their maximum size which, at times, does not fit within the screen and makes watching the video on the watch page uncomfortable.

Possible Solution :
Set parameters for uploaded videos not to exceed a certain area of the watch page. By doing this, any video that is uploaded will be resized to fit within an acceptable area of the watch page, allowing the uploader to upload content without the extra work of resizing their footage on their end while also allowing the viewer an easier time watching.

**Comment by UtkuBulkan** [comment]
The videos exceed the expected area on the watch page, that is correct. However, it only exceeds in terms of height, not width. It is not mandatory to change the trancoded size of the video content, but only having a maximum height on the watch page could be sufficient to overcome this problem.

**Comment by zrabbani** [comment]
I agree with that, as long as the video does not sink beneath the visible webpage any solution would work.

**Comment by UtkuBulkan** [comment]
@zrabbani, Video aspect ratio and height is now fixed for mobile and web, please check and confirm.

Following confirmation please close with latest testing results.

**Comment by zrabbani** [comment]
The videos are all well sized now
good fix
closing issue
